# Generated by Django 2.1.7 on 2019-03-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='main.Keyword'),
        ),
    ]
