# Generated by Django 2.1.4 on 2019-03-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_scaleflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cheese',
            field=models.BooleanField(default=False),
        ),
    ]
