# Generated by Django 2.1.4 on 2019-03-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190326_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='timeOfEnd',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='timeOfStart',
            field=models.DateTimeField(blank=True),
        ),
    ]
